publisher_gripper_controller:
  ros__parameters:

    controller_name: "gripper_controller"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3"]
    pos1: [0.0, 0.0, 0.0, 0.0]
    pos2: [0.05, 0.05, 0.05, 0.05]
    pos3: [0.10, 0.05, 0.10, 0.05]