controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController


gripper_controller:
  ros__parameters:
    joints:
      - joint_cylinder_back_left
      - joint_cylinder_back_right
      - joint_cylinder_front_left
      - joint_cylinder_front_right
    interface_name: position

position_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6